# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/bin/cmake

# The command to remove a file.
RM = /opt/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rob/projects/65co2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rob/projects/65co2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rob/projects/65co2/CMakeFiles /home/rob/projects/65co2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rob/projects/65co2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testcpu

# Build rule for target.
testcpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testcpu
.PHONY : testcpu

# fast build rule for target.
testcpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testcpu.dir/build.make CMakeFiles/testcpu.dir/build
.PHONY : testcpu/fast

#=============================================================================
# Target rules for targets named apple1

# Build rule for target.
apple1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apple1
.PHONY : apple1

# fast build rule for target.
apple1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/build
.PHONY : apple1/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/Cpu/65co2.o: src/Cpu/65co2.cpp.o
.PHONY : src/Cpu/65co2.o

# target to build an object file
src/Cpu/65co2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testcpu.dir/build.make CMakeFiles/testcpu.dir/src/Cpu/65co2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/Cpu/65co2.cpp.o
.PHONY : src/Cpu/65co2.cpp.o

src/Cpu/65co2.i: src/Cpu/65co2.cpp.i
.PHONY : src/Cpu/65co2.i

# target to preprocess a source file
src/Cpu/65co2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testcpu.dir/build.make CMakeFiles/testcpu.dir/src/Cpu/65co2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/Cpu/65co2.cpp.i
.PHONY : src/Cpu/65co2.cpp.i

src/Cpu/65co2.s: src/Cpu/65co2.cpp.s
.PHONY : src/Cpu/65co2.s

# target to generate assembly for a file
src/Cpu/65co2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testcpu.dir/build.make CMakeFiles/testcpu.dir/src/Cpu/65co2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/Cpu/65co2.cpp.s
.PHONY : src/Cpu/65co2.cpp.s

src/apple1.o: src/apple1.cpp.o
.PHONY : src/apple1.o

# target to build an object file
src/apple1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/apple1.cpp.o
.PHONY : src/apple1.cpp.o

src/apple1.i: src/apple1.cpp.i
.PHONY : src/apple1.i

# target to preprocess a source file
src/apple1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/apple1.cpp.i
.PHONY : src/apple1.cpp.i

src/apple1.s: src/apple1.cpp.s
.PHONY : src/apple1.s

# target to generate assembly for a file
src/apple1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/apple1.cpp.s
.PHONY : src/apple1.cpp.s

src/apple1stdio.o: src/apple1stdio.cpp.o
.PHONY : src/apple1stdio.o

# target to build an object file
src/apple1stdio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/apple1stdio.cpp.o
.PHONY : src/apple1stdio.cpp.o

src/apple1stdio.i: src/apple1stdio.cpp.i
.PHONY : src/apple1stdio.i

# target to preprocess a source file
src/apple1stdio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/apple1stdio.cpp.i
.PHONY : src/apple1stdio.cpp.i

src/apple1stdio.s: src/apple1stdio.cpp.s
.PHONY : src/apple1stdio.s

# target to generate assembly for a file
src/apple1stdio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/apple1stdio.cpp.s
.PHONY : src/apple1stdio.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apple1.dir/build.make CMakeFiles/apple1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/testcpu.o: src/testcpu.cpp.o
.PHONY : src/testcpu.o

# target to build an object file
src/testcpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testcpu.dir/build.make CMakeFiles/testcpu.dir/src/testcpu.cpp.o
.PHONY : src/testcpu.cpp.o

src/testcpu.i: src/testcpu.cpp.i
.PHONY : src/testcpu.i

# target to preprocess a source file
src/testcpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testcpu.dir/build.make CMakeFiles/testcpu.dir/src/testcpu.cpp.i
.PHONY : src/testcpu.cpp.i

src/testcpu.s: src/testcpu.cpp.s
.PHONY : src/testcpu.s

# target to generate assembly for a file
src/testcpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testcpu.dir/build.make CMakeFiles/testcpu.dir/src/testcpu.cpp.s
.PHONY : src/testcpu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... apple1"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... testcpu"
	@echo "... src/Cpu/65co2.o"
	@echo "... src/Cpu/65co2.i"
	@echo "... src/Cpu/65co2.s"
	@echo "... src/apple1.o"
	@echo "... src/apple1.i"
	@echo "... src/apple1.s"
	@echo "... src/apple1stdio.o"
	@echo "... src/apple1stdio.i"
	@echo "... src/apple1stdio.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/testcpu.o"
	@echo "... src/testcpu.i"
	@echo "... src/testcpu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

