
REM SUPER STARTREK - MAY 16,1978 - REQUIRES 24K MEMORY
REM ****        **** STAR TREK ****        ****
REM **** SIMULATION OF A MISSION OF THE STARSHIP ENTERPRISE,
REM **** AS SEEN ON THE STAR TREK TV SHOW.
REM **** ORIGIONAL PROGRAM BY MIKE MAYFIELD, MODIFIED VERSION
REM **** PUBLISHED IN DEC'S "101 BASIC GAMES", BY DAVE AHL.
REM **** MODIF ICATIONS TO THE LATTER (PLUS DEBUGGING) BY BOB
REM *** LEEDOM - APRIL & DECEMBER 1974,
REM *** WITH A LITTLE HELP FROM HIS FRIENDS . . .
REM *** COMMENTS, EPITHETS, AND SUGGESTIONS SOLICITED --
REM *** SEND TO:  R. C. LEEDOM
REM ***           WESTINGHOUSE DEFENSE & ELECTRONICS SYSTEMS CNTR.
REM ***           BOX 746, M.S. 338
REM ***           BALTIMORE, MD  21203
REM ***
REM *** CONVERTED  TO MICROSOFT 8 K BASIC 3/16/78 BY JOHN GORDERS
REM *** LINE NUMBERS FROM VERSION STREK7 OF 1/12/75 PRESERVED AS
REM *** MUCH AS POSSIBLE WHILE USING MULTIPLE STATEMENTS PER LINE
REM *** SOME LINES ARE LONGER THAN 72 CHARACTERS; THIS WAS DONE
REM *** BY USING "?" INSTEAD OF "PRINT " WHEN ENTERING LINES
REM *** (fixed for applesoft sometime in 2014... finally)
10 ?"HELLO WORLD"

RUN
